### ISSUE TITLE
"/online-dictionary/online-dictionary.csproj": not found

### ISSUE THREAD

**Issue by hiaux0** [midnight-animals/midnight-highgrass-code#5]
=> ERROR [online-dictionary build 3/7] COPY [online-dictionary/online-dictionary.csproj, online-dictionary/]  0.0s

------
 > [online-dictionary build 3/7] COPY [online-dictionary/online-dictionary.csproj, online-dictionary/]:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref fc0d7e5d-5866-4d31-8ce1-e86d0862c391::kzkzbjklj9uujds3lq1brij8w: "/online-dictionary/online-dictionary.csproj": not found

![image](https://github.com/midnight-animals/midnight-highgrass-code/assets/30693990/c810932d-5966-410e-bd4d-a820204f91c4)

**Comment by JaclyNolan** [comment]
a06d21057b7f0e0503efc3051e6e42f1a2fb6ce1
- Added the recommeneded gitignore file (idk why this isn't the one when running dotnet new gitignore... Damn you MS)
